### ISSUE TITLE
The AudioWorkletGlobalScope property in globals.browser breaks ESLint

### ISSUE THREAD

**Issue by Polcio** [sindresorhus/globals#239]
![image](https://github.com/sindresorhus/globals/assets/22074530/7c36ce69-cce5-4adc-b01e-eb46ce363dec)

As shown in the picture above, the `AudioWorkletGlobalScope` property has a trailing space, leading to a runtime error thrown by the ESLint server

![image](https://github.com/sindresorhus/globals/assets/22074530/97ba0e7e-7fd6-4492-8ca7-0332a39f4d31)

The trailing whitespace should be removed. For now, I'll manually parse the `globals.browser` object, `trim`ming every property before spreading the object into my flat ESLint config.

### Update
Here's my workaround:

```js
const GLOBALS_BROWSER_FIX = Object.assign({}, globals.browser, {
    AudioWorkletGlobalScope: globals.browser['AudioWorkletGlobalScope ']
});

delete GLOBALS_BROWSER_FIX['AudioWorkletGlobalScope '];

// ESLint flat config:
[
    // config objects
    {
        // stuff
        languageOptions: {
            globals: {
                ...GLOBALS_BROWSER_FIX
            }
        }
        // other stuff
    }
    // other config objects
]
```

**Comment by fisker** [comment]
This was fixed 2 years ago, https://github.com/sindresorhus/globals/pull/184

**Comment by georgeonofrei** [comment]
I've manually installed globals v15.9.0 and this is still an issue.

**Comment by dimaslanjaka** [comment]
I think this caused by globals package, on my workspace got warn message too, but still working on fixing lint `eslint --fix`

**Comment by aliesenli** [comment]
I've checked the latest version and inspected the `globals.json` file, and it appears to be fixed. However, when I install it via npm i -g globals, the trailing space reappears. I'm not sure why this is happening— it seems like something is being cached somewhere, but I'm not sure where. Even after deleting and reinstalling, the issue persists.

**Comment by aliesenli** [comment]
> Still happening on version "globals": "^15.11.0",

This most likely happens because you might have `peer-dependencies` that still rely on older version of `globals` package...

Run the following command in your repo to see which packages depend on older versions of globals:
`npm ls globals`

**Comment by Trevodorax** [comment]
> > Still happening on version "globals": "^15.11.0",
> 
> This most likely happens because you might have `peer-dependencies` that still rely on older version of `globals` package...
> 
> Run the following command in your repo to see which packages depend on older versions of globals: `npm ls globals`

How would you go about solving this if we have a lib that requires an old version ?

**Comment by aliesenli** [comment]
> > > Still happening on version "globals": "^15.11.0",
> > 
> > 
> > This most likely happens because you might have `peer-dependencies` that still rely on older version of `globals` package...
> > Run the following command in your repo to see which packages depend on older versions of globals: `npm ls globals`
> 
> How would you go about solving this if we have a lib that requires an old version ?

Updating your dependencies might solve your issue. 

Another alternative is to use patch-package https://www.npmjs.com/package/patch-package to patch some dependencies and commit these to git. Here is an example of patching this specific error: https://github.com/amzn/style-dictionary/pull/1386/files#diff-7769c40c31a3fd64fd477d0b5b4c020f19e223893450a0acf4b5946c5ff235bd

**Comment by pawelataman** [comment]
in eslint.config.js `

const browserGlobals = {
  ...globals.browser,
  AudioWorkletGlobalScope: false // this is the default,
};

delete browserGlobals['AudioWorkletGlobalScope ']; // Remove the space at the end`

and then:

`languageOptions: {
      globals: {
        ...globals.node,
        ...browserGlobals,
      },
    },`

**Comment by danythedev01** [comment]
I just installed globals and it worked for me. Version is "^16.4.0"
